### ISSUE TITLE
WS10 support

### ISSUE THREAD

**Issue by evliu** [johnlindquist/Darkerula#1]
This is my favorite part of WS9; Can this be moved to WS10? Thanks!

**Comment by montyr75** [comment]
Another vote for this! Any plans to update your hack for version 10, John?

**Comment by apsolut** [comment]
PS10 dont support this (failed and disabled on start).. +1

**Comment by Gamrix** [comment]
Same with Android Studio 3. Error at startup:

```
Plugin 'com.johnlindquist.Darkerula' failed to initialize and will be disabled.  Please restart Android Studio.

java.lang.NoSuchMethodError: com.intellij.openapi.editor.colors.impl.EditorColorsSchemeImpl.<init>(Lcom/intellij/openapi/editor/colors/EditorColorsScheme;Lcom/intellij/openapi/editor/colors/ex/DefaultColorSchemesManager;)V
    at DarkerulaApplicationComponent.loadSchemeFromDocument(DarkerulaApplicationComponent.java:104)
    at DarkerulaApplicationComponent.loadSchemeFromStream(DarkerulaApplicationComponent.java:94)
    at DarkerulaApplicationComponent.loadScheme(DarkerulaApplicationComponent.java:71)
    at DarkerulaApplicationComponent.initComponent(DarkerulaApplicationComponent.java:31)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:497)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:119)
    at com.intellij.openapi.application.impl.ApplicationImpl.lambda$createComponents$9(ApplicationImpl.java:447)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:543)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:488)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:454)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:103)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:406)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:392)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:206)
    at com.intellij.idea.MainImpl$1.lambda$null$0(MainImpl.java:49)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
    at java.awt.EventQueue.access$500(EventQueue.java:98)
    at java.awt.EventQueue$3.run(EventQueue.java:715)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:346)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```
